### PR TITLE
pylint to precommit

### PR DESCRIPTION
**Pull request by FoamyGuy**

### CODE REVIEW

**Review by kattni — APPROVED** [review]

**Review by kattni — CHANGES_REQUESTED** [review]
Actually, this failure brings up a question about how to run Pylint on `/tests`. Please don't merge it yet. Thanks!

**Review by kattni — CHANGES_REQUESTED** [review]
@FoamyGuy If you're up for it, please add another pre-commit hook, similar to the `pylint_examples` commit hook, except call it `pylint_tests`, and for the `disable`, only include `disable=missing-docstring` (leave out `invalid name`). Update the `name:` and `desciption:` to fit with what the hook will be doing.

If you're not up for it, please let me know and I'll take care of it. Thanks!

**Comment by FoamyGuy** [comment]
@kattni I think the new hook for pylint_tests is set up now. However it did flag several items in the existing test scripts.

**Review by kattni — APPROVED** [review]
@FoamyGuy The failures were expected. We'll deal with them next week when @brentru has returned. Thanks for getting this added!

**Pull request merged**
